[package]
name = "bevyacad"
version = "0.1.0"
authors = ["King-Coyote <alex.hartstone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {github = "https://github.com/bevyengine/bevy", features = ["dynamic"]}
bevy_htn = { path = "crates/bevy_htn", version = "^0.1.0"}