[package]
name = "bevy_htn"
version = "0.1.0"
authors = ["alex.hartstone@gmail.com <alex.hartstone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "^0"